spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_shop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: "123456"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  security:
#    jwt:
#      secret: "javainuse"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloudinary:
  api-key: 941645277557341
  api-secret: ${CLOUDINERY_API_SECRET}
  cloud-name: dj0dxejrk

example:
  app:
    jwtSecret: MySecretKey
    jwtExpirationMs: 86400000